/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Facturacion;
import Datos.Usuario;
import Logica.OperacionesFacturacion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class VentanaAnularFactura extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAnularFactura
     */
    public VentanaAnularFactura() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private Usuario datosUsuario;

    public Usuario getDatosUsuario() {
        return datosUsuario;
    }

    public void setDatosUsuario(Usuario datosUsuario) {
        this.datosUsuario = datosUsuario;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        jLabelFacturaNro = new javax.swing.JLabel();
        jTextFieldNumFactura = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonCancelar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FastFoodSystem - Anular Factura");
        setMaximumSize(new java.awt.Dimension(586, 225));
        setMinimumSize(new java.awt.Dimension(586, 225));

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese el Numero de Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        jLabelFacturaNro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelFacturaNro.setText("Factura Nro:");

        jTextFieldNumFactura.setMaximumSize(new java.awt.Dimension(210, 20));
        jTextFieldNumFactura.setMinimumSize(new java.awt.Dimension(210, 20));
        jTextFieldNumFactura.setPreferredSize(new java.awt.Dimension(210, 20));

        jButtonBuscar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-buscar.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelFacturaNro)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFacturaNro)
                    .addComponent(jTextFieldNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButtonCancelar2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-cancelar.png"))); // NOI18N
        jButtonCancelar2.setText("Salir");
        jButtonCancelar2.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar2.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar2.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarCampos(){
        try{
            Long.parseLong(jTextFieldNumFactura.getText());
            if(jTextFieldNumFactura.getText().length() <= 0){
                JOptionPane.showMessageDialog(this, "ERROR: El Numero de Factura No Debe Ser Vacio", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            Integer.parseInt(jTextFieldNumFactura.getText());
            }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ERROR: El Numero de Factura Debe Ser Numerico", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
        
    }   
    
    
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        Facturacion res =  null;
        if (validarCampos()) {
            OperacionesFacturacion OF = new OperacionesFacturacion();
            
           
            try {
                res = OF.buscarFactura(Integer.parseInt(jTextFieldNumFactura.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(VentanaAnularFactura.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VentanaAnularFactura.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(res!=null){
                if(!res.isEstado()){
                    JOptionPane.showMessageDialog(this, "ERROR: La Factura Ya Esta Anulada", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            
                }else{
            VentanaConfirmacion VC = new VentanaConfirmacion();
            VC.setFactura(res);
            VC.setDatosUsuario(datosUsuario);
            VC.cargarDatos();
            VC.setVisible(true);
            this.dispose();}
//            if(!res){
//                 JOptionPane.showMessageDialog(this, "La Factura Se Anulo Correctamente", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
//            }
            }else{
                 JOptionPane.showMessageDialog(this, "ERROR: La Factura Inexistente", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            }
//            if(res == 0){
//                 JOptionPane.showMessageDialog(this, "La Factura No Se Puede Anular", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
//            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAnularFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar2;
    private javax.swing.JLabel jLabelFacturaNro;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JTextField jTextFieldNumFactura;
    // End of variables declaration//GEN-END:variables
}
