/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Usuario;
import Datos.Zona;
import Logica.ABMUsuario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gonzalez
 */
public class VentanaGestionarZonas extends javax.swing.JFrame {

    private TableRowSorter trsFiltro;
    private DefaultTableModel modelo;
    Usuario usuarioSistema;

    /**
     * Creates new form GestionarUsuarip
     */
    public VentanaGestionarZonas() throws ClassNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jButtonEliminarZona.setEnabled(false);
        jButtonModificarZona.setEnabled(false);
        String cabecera[] = {"Id", "Descripcion", "Precio"};
        String datos[][] = {};
        modelo = new DefaultTableModel(datos, cabecera);
        jTableUsuario.setModel(modelo);
        cargarTablaZonas();
        jButtonCancelarSelecc.setBackground(java.awt.Color.red);
        jButtonCancelarSelecc.setEnabled(false);
        jTableUsuario.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int fila = jTableUsuario.rowAtPoint(e.getPoint());
                int columna = jTableUsuario.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
                    jButtonEliminarZona.setEnabled(true);
                    jButtonModificarZona.setEnabled(true);
                    jButtonNuevaZona.setEnabled(false);
                    jButtonCancelarSelecc.setEnabled(true);
                }
            }
        });
        usuarioSistema = new Usuario();

    }

    public Usuario getUsuarioSistema() {
        return usuarioSistema;
    }

    public void setUsuarioSistema(Usuario usuarioSistema) {
        this.usuarioSistema = usuarioSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscarZona = new javax.swing.JPanel();
        jLabelDescripcion = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jButtonNuevaZona = new javax.swing.JButton();
        jButtonModificarZona = new javax.swing.JButton();
        jButtonEliminarZona = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jButtonCancelarSelecc = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FastFoodSystem - Gestionar Zona");

        jPanelBuscarZona.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Zona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        jLabelDescripcion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDescripcion.setText("Descripcion:");

        jTextFieldDescripcion.setMaximumSize(new java.awt.Dimension(210, 20));
        jTextFieldDescripcion.setMinimumSize(new java.awt.Dimension(210, 20));
        jTextFieldDescripcion.setPreferredSize(new java.awt.Dimension(210, 20));
        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });
        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarZonaLayout = new javax.swing.GroupLayout(jPanelBuscarZona);
        jPanelBuscarZona.setLayout(jPanelBuscarZonaLayout);
        jPanelBuscarZonaLayout.setHorizontalGroup(
            jPanelBuscarZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarZonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescripcion)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBuscarZonaLayout.setVerticalGroup(
            jPanelBuscarZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarZonaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelBuscarZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcion)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonNuevaZona.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonNuevaZona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-zona.png"))); // NOI18N
        jButtonNuevaZona.setText("Nuevo Zona");
        jButtonNuevaZona.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonNuevaZona.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonNuevaZona.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonNuevaZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaZonaActionPerformed(evt);
            }
        });

        jButtonModificarZona.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonModificarZona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-zona.png"))); // NOI18N
        jButtonModificarZona.setText("Modificar Zona");
        jButtonModificarZona.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonModificarZona.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonModificarZona.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonModificarZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarZonaActionPerformed(evt);
            }
        });

        jButtonEliminarZona.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonEliminarZona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-delete.png"))); // NOI18N
        jButtonEliminarZona.setText("Eliminar Zona");
        jButtonEliminarZona.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonEliminarZona.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonEliminarZona.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonEliminarZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarZonaActionPerformed(evt);
            }
        });

        jTableUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableUsuario);
        if (jTableUsuario.getColumnModel().getColumnCount() > 0) {
            jTableUsuario.getColumnModel().getColumn(0).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(1).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(2).setResizable(false);
        }

        jButtonCancelarSelecc.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancelarSelecc.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonCancelarSelecc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarSelecc.setText("Cancelar seleccion");
        jButtonCancelarSelecc.setMaximumSize(new java.awt.Dimension(180, 140));
        jButtonCancelarSelecc.setMinimumSize(new java.awt.Dimension(180, 140));
        jButtonCancelarSelecc.setPreferredSize(new java.awt.Dimension(180, 140));
        jButtonCancelarSelecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarSeleccActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iconos_Botones/icono-cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(180, 50));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonCancelarSelecc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNuevaZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jButtonModificarZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButtonEliminarZona, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jPanelBuscarZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelBuscarZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevaZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarSelecc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        if (validarCampoNombreUsu()) {
            ABMUsuario BU = new ABMUsuario();
            Usuario U = new Usuario();
            try {
                U = BU.buscarUsuario(String.valueOf(jTextFieldDescripcion.getText()));
                if (U == null) {
                    JOptionPane.showMessageDialog(this, "El Usuario No Existe\nPara registrarlo presione \"Nuevo Usuario\"", "FastFoodSystem", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jTextFieldDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionKeyReleased

    private void jTextFieldDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyTyped
        jTextFieldDescripcion.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                trsFiltro.setRowFilter(RowFilter.regexFilter("(?i)" + jTextFieldDescripcion.getText(), 1));
            }
        });

        trsFiltro = new TableRowSorter(jTableUsuario.getModel());
        jTableUsuario.setRowSorter(trsFiltro);
        jTableUsuario.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int fila = jTableUsuario.rowAtPoint(e.getPoint());
                int columna = jTableUsuario.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
                    jButtonEliminarZona.setEnabled(true);
                    jButtonModificarZona.setEnabled(true);
                    jButtonNuevaZona.setEnabled(false);
                    jButtonCancelarSelecc.setEnabled(true);
                }
            }
        });
    }//GEN-LAST:event_jTextFieldDescripcionKeyTyped

    private void jButtonNuevaZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaZonaActionPerformed
        
        int fila = jTableUsuario.getSelectedRow();

        
        
        VentanaZonas VZ = new VentanaZonas();
        try {
            VZ.LlenarCampos(1,0, "", 0);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        VZ.setCondatos_vacio(0);
        
        VZ.setUsuarioSistema(usuarioSistema);
        System.out.println(usuarioSistema.getTipoUsuario());
        VZ.setVisible(true);
        this.dispose();
        
      
    }//GEN-LAST:event_jButtonNuevaZonaActionPerformed

    private void jButtonModificarZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarZonaActionPerformed
        int fila = jTableUsuario.getSelectedRow();

        int id = (int) jTableUsuario.getValueAt(fila, 0);
        String des = String.valueOf(jTableUsuario.getValueAt(fila, 1));
       float pre = Float.parseFloat(String.valueOf(jTableUsuario.getValueAt(fila, 2)));
        VentanaZonas VZ = new VentanaZonas();      
        VZ.setCondatos_vacio(1);
        try {
            VZ.LlenarCampos(3, id, des, pre);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
        }
           
       
        
        
        VZ.setUsuarioSistema(usuarioSistema);
        System.out.println(usuarioSistema.getTipoUsuario());
        VZ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonModificarZonaActionPerformed

    private void jButtonEliminarZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarZonaActionPerformed
        int fila = jTableUsuario.getSelectedRow();

        int id = (int) jTableUsuario.getValueAt(fila, 0);
        String des = String.valueOf(jTableUsuario.getValueAt(fila, 1));
        float pre = (float)(jTableUsuario.getValueAt(fila, 2));
        
        VentanaZonas VZ = new VentanaZonas();
        VZ.setCondatos_vacio(1);
        try {
            try {
                VZ.LlenarCampos(2, id, des, pre);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
        VZ.setUsuarioSistema(usuarioSistema);
        System.out.println(usuarioSistema.getTipoUsuario());
        VZ.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonEliminarZonaActionPerformed

    private void jButtonCancelarSeleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarSeleccActionPerformed
        jTableUsuario.clearSelection();
        jButtonEliminarZona.setEnabled(false);
        jButtonModificarZona.setEnabled(false);
        jButtonNuevaZona.setEnabled(true);
        jButtonCancelarSelecc.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarSeleccActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void cargarTablaZonas() throws ClassNotFoundException {
        ResultSet Re;
        Zona Z = new Zona();
        Re = Z.consultarTodasLasZonas();
        try {
            while (Re.next()) {
                boolean estado = Re.getBoolean("estado");
                if(estado){
                int id = Re.getInt("idZona");
                String des = Re.getString("Descripcion");
                float pre = Re.getInt("precio");
                
                
                Object fila[] = {id,des,pre};
                modelo.addRow(fila);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean validarCampoNombreUsu() {
        if (jTextFieldDescripcion.getText().length() > 0) {
            if (jTextFieldDescripcion.getText().length() <= 20) {
                if (jTextFieldDescripcion.getText().matches("[A-Za-z\\s]+")) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "ERROR: El Nombre De Usuario Debe Contener Solo Letras", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Nombre de Usuario\" No Debe Contener Mas de 20 Caracteres", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: El Campo \"Nombre de Usuario\" No Debe Estar Vacio", "FastFoodSystem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarZonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarZonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarZonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarZonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaGestionarZonas().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VentanaGestionarZonas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelarSelecc;
    private javax.swing.JButton jButtonEliminarZona;
    private javax.swing.JButton jButtonModificarZona;
    private javax.swing.JButton jButtonNuevaZona;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JPanel jPanelBuscarZona;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables

}
